### ISSUE TITLE
v2.0.1 causes fatal error in Joplin editor

### ISSUE THREAD

**Issue by AJSchiller** [jannessm/joplin-zotero-link#18]
After updating the plugin to v2.0.1, encounter the following error. Can now only use Joplin when Zotero Link is disabled. (Version details included in error message. ETA: this is on Linux Mint 21.3.)

```
Error
The text editor encountered a fatal error and could not continue. The error might be due to a plugin, so please try to disable some of them and try again.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/jannessm/joplin-zotero-link/issues/new#), which will temporarily disable all plugins.

Message
Cannot read properties of undefined (reading 'completionSource')

Version info
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.20 (prod, linux)

Client ID: d280859c5f2b41668d10c48bc9fcf809
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: 8199362

Backup: 1.4.2
Quick Links: 1.3.2
Zotero Link: 2.0.1
Plugins
[
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.2"
    },
    {
        "id": "nz.magnusso.zotero-link",
        "name": "Zotero Link",
        "enabled": true,
        "version": "2.0.1"
    },
    {
        "id": "com.whatever.quick-links",
        "name": "Quick Links",
        "enabled": true,
        "version": "1.3.2"
    }
]
Stack trace
TypeError: Cannot read properties of undefined (reading 'completionSource')
    at CodeMirror.<anonymous> (/home/user/.config/joplin-desktop/cache/nz.magnusso.zotero-link/zotero-link.js:1:1411)
    at /tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/codemirror/lib/codemirror.js:3968:22
    at CodeMirror.setOption (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/codemirror/lib/codemirror.js:8304:52)
    at /tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/v5/Editor.js:238:24
    at commitHookEffectListMount (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24917:7)
    at commitPassiveMountEffects (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:27078:3)
Component stack

    at Editor (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/v5/Editor.js:76:54)
    at div
    at div
    at div
    at ErrorBoundary (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/ErrorBoundary.js:12:9)
    at CodeMirror (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.js:37:44)
    at div
    at div
    at div
    at NoteEditor (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/NoteEditor/NoteEditor.js:61:68)
    at ConnectFunction (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at div
    at I (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at div
    at div
    at ResizableLayout (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/ResizableLayout/ResizableLayout.js:54:45)
    at div
    at MainScreenComponent (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/MainScreen/MainScreen.js:69:9)
    at ConnectFunction (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at div
    at NavigatorComponent (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/Navigator.js:7:1)
    at ConnectFunction (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at exports.ThemeProvider (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:25001)
    at ae (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:13440)
    at RootComponent (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/Root.js:93:1)
    at ConnectFunction (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at ErrorBoundary (/tmp/.mount_Joplin7Acn5p/resources/app.asar/gui/ErrorBoundary.js:12:9)
    at Provider (/tmp/.mount_Joplin7Acn5p/resources/app.asar/node_modules/react-redux/lib/components/Provider.js:19:3)
```

**Comment by AJSchiller** [comment]
Thank you, that fixed the issue.
