### ISSUE TITLE
Text Editor failed after installing the plugin

### ISSUE THREAD

**Issue by TYJ02** [jannessm/joplin-zotero-link#20]
Error
The text editor encountered a fatal error and could not continue. The error might be due to a plugin, so please try to disable some of them and try again.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to restart in safe mode, which will temporarily disable all plugins.

Message
Cannot read properties of undefined (reading 'completionSource')

Version info
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.23 (prod, linux)

Client ID: 64a00043906e4fe6977c81982843e0fc
Sync Version: 3
Profile Version: 47
Keychain Supported: No

Revision: b3ea12784

Automatic Backlinks to note: 3.0.3
Backup: 1.4.2
BibTeX: 0.5.0
Calendar: 1.1.1
CodeMirror 6 snippets: 0.0.8
CodeMirror Options: 1.1.0
Custom CodeMirror .vimrc: 1.0.6
Event Calendar: 0.2.2
Inline TODO: 1.7.1
Link Graph UI: 1.5.0
macOS theme: 1.5.8
Note Link System: 0.8.0
Note Rename: 1.0.0
Note Tabs: 1.4.0
OCR: 0.3.2
Outline: 1.5.13
Plugin Bundle: 0.5.5
Quick Goto: 1.2.0
Rich Markdown: 0.14.1
VS-Code Style Note Search: 0.2.2
...
Plugins
[
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": true,
        "version": "1.4.0"
    },
    {
        "id": "joplin.plugin.ambrt.backlinksToNote",
        "name": "Automatic Backlinks to note",
        "enabled": true,
        "version": "3.0.3"
    },
    {
        "id": "ylc395.noteLinkSystem",
        "name": "Note Link System",
        "enabled": true,
        "version": "0.8.0"
    },
    {
        "id": "com.andrejilderda.macOSTheme",
        "name": "macOS theme",
        "enabled": true,
        "version": "1.5.8"
    },
    {
        "id": "org.joplinapp.plugins.joplin-calendar",
        "name": "Calendar",
        "enabled": true,
        "version": "1.1.1"
    },
    {
        "id": "io.treymo.LinkGraph",
        "name": "Link Graph UI",
        "enabled": true,
        "version": "1.5.0"
    },
    {
        "id": "com.wemakemachines.joplin.plugin.event-calendar",
        "name": "Event Calendar",
        "enabled": false,
        "version": "0.2.2"
    },
    {
        "id": "plugin.calebjohn.todo",
        "name": "Inline TODO",
        "enabled": false,
        "version": "1.7.1"
    },
    {
        "id": "joplin.plugin.cmoptions",
        "name": "CodeMirror Options",
        "enabled": true,
        "version": "1.1.0"
    },
    {
        "id": "outline",
        "name": "Outline",
        "enabled": true,
        "version": "1.5.13"
    },
    {
        "id": "com.hieuthi.joplin.quick-goto",
        "name": "Quick Goto",
        "enabled": true,
        "version": "1.2.0"
    },
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.2"
    },
    {
        "id": "com.cuibonobo.NoteRename",
        "name": "Note Rename",
        "enabled": false,
        "version": "1.0.0"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": false,
        "version": "0.14.1"
    },
    {
        "id": "com.septemberhx.pluginBundle",
        "name": "Plugin Bundle",
        "enabled": false,
        "version": "0.5.5"
    },
    {
        "id": "com.isquaredsoftware.joplin-plugin-vscode-style-search",
        "name": "VS-Code Style Note Search",
        "enabled": true,
        "version": "0.2.2"
    },
    {
        "id": "ylc395.joplinOcr",
        "name": "OCR",
        "enabled": false,
        "version": "0.3.2"
    },
    {
        "id": "io.github.personalizedrefrigerator.snippets-and-autocomplete",
        "name": "CodeMirror 6 snippets",
        "enabled": true,
        "version": "0.0.8"
    },
    {
        "id": "io.github.personalizedrefrigerator.joplin-vimrc",
        "name": "Custom CodeMirror .vimrc",
        "enabled": false,
        "version": "1.0.6"
    },
    {
        "id": "com.xUser5000.bibtex",
        "name": "BibTeX",
        "enabled": true,
        "version": "0.5.0"
    },
    {
        "id": "nz.magnusso.zotero-link",
        "name": "Zotero Link",
        "enabled": true,
        "version": "2.0.1"
    }
]
Stack trace
TypeError: Cannot read properties of undefined (reading 'completionSource')
    at CodeMirror.<anonymous> (/home/yujing/snap/joplin-desktop/87/.config/joplin-desktop/cache/nz.magnusso.zotero-link/zotero-link.js:1:1411)
    at /snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/codemirror/lib/codemirror.js:3968:22
    at CodeMirror.setOption (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/codemirror/lib/codemirror.js:8304:52)
    at /snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/v5/Editor.js:238:24
    at commitHookEffectListMount (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24917:7)
    at commitPassiveMountEffects (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:27078:3)
Component stack

    at Editor (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/v5/Editor.js:76:54)
    at div
    at div
    at div
    at ErrorBoundary (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/ErrorBoundary.js:12:9)
    at CodeMirror (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/NoteEditor/NoteBody/CodeMirror/v5/CodeMirror.js:37:44)
    at div
    at div
    at div
    at NoteEditor (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/NoteEditor/NoteEditor.js:61:68)
    at ConnectFunction (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at div
    at I (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:19269)
    at div
    at Resizable (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/re-resizable/lib/index.es5.js:220:28)
    at div
    at Resizable (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/re-resizable/lib/index.es5.js:220:28)
    at div
    at ResizableLayout (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/ResizableLayout/ResizableLayout.js:54:45)
    at div
    at MainScreenComponent (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/MainScreen/MainScreen.js:69:9)
    at ConnectFunction (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at div
    at NavigatorComponent (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/Navigator.js:7:1)
    at ConnectFunction (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at exports.ThemeProvider (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:25001)
    at ae (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/styled-components/dist/styled-components.cjs.js:1:13440)
    at RootComponent (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/Root.js:93:1)
    at ConnectFunction (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-redux/lib/components/connect.js:246:74)
    at ErrorBoundary (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/gui/ErrorBoundary.js:12:9)
    at Provider (/snap/joplin-desktop/87/opt/joplin-desktop/resources/app.asar/node_modules/react-redux/lib/components/Provider.js:19:3)

**Comment by jannessm** [comment]
Please use a version < 2.0 if you want to use this plugin with codemirror 5 (legacy mode).
