### ISSUE TITLE
Issue after installing the plugin

### ISSUE THREAD

**Issue by KrullTheWarriorKing** [jannessm/joplin-zotero-link#22]
Hello, after installing the zotzerver and the plugin, I got this error :

Error
The text editor encountered a fatal error and could not continue. The error might be due to a plugin, so please try to disable some of them and try again.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/jannessm/joplin-zotero-link/issues/new#), which will temporarily disable all plugins.

Message
Cannot read properties of undefined (reading 'completionSource')

Version info
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.24 (prod, win32)

Client ID: 833f47eae267427287c115a5114667e1
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: d581264

Backup: 1.4.2
Favorites: 1.3.2
Graph: 1.1.0
Jarvis: 0.9.1
Kminder Mindmap: 0.8.6
Link Graph UI: 1.5.0
Note Link System: 0.8.0
Note Tabs: 1.4.0
PlantUML2: 1.11.0
Quick Links: 1.3.2
Rich Markdown: 0.15.1
Templates: 2.4.0
Zotero Link: 2.0.1
Plugins
[
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": true,
        "version": "1.4.0"
    },
    {
        "id": "joplin.plugin.benji.favorites",
        "name": "Favorites",
        "enabled": true,
        "version": "1.3.2"
    },
    {
        "id": "com.whatever.quick-links",
        "name": "Quick Links",
        "enabled": true,
        "version": "1.3.2"
    },
    {
        "id": "ylc395.noteLinkSystem",
        "name": "Note Link System",
        "enabled": true,
        "version": "0.8.0"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": true,
        "version": "0.15.1"
    },
    {
        "id": "com.github.marc0l92.joplin-plugin-plantUML",
        "name": "PlantUML2",
        "enabled": true,
        "version": "1.11.0"
    },
    {
        "id": "calandra.kminder.joplin",
        "name": "Kminder Mindmap",
        "enabled": true,
        "version": "0.8.6"
    },
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.2"
    },
    {
        "id": "joplin-plugin-knowledge-graph",
        "name": "Graph",
        "enabled": true,
        "version": "1.1.0"
    },
    {
        "id": "joplin.plugin.templates",
        "name": "Templates",
        "enabled": true,
        "version": "2.4.0"
    },
    {
        "id": "joplin.plugin.alondmnt.jarvis",
        "name": "Jarvis",
        "enabled": true,
        "version": "0.9.1"
    },
    {
        "id": "io.treymo.LinkGraph",
        "name": "Link Graph UI",
        "enabled": true,
        "version": "1.5.0"
    },
    {
        "id": "nz.magnusso.zotero-link",
        "name": "Zotero Link",
        "enabled": true,
        "version": "2.0.1"
    }
]
Stack trace
TypeError: Cannot read properties of undefined (reading 'completionSource')
    at CodeMirror.<anonymous> (C:\Users\gaultiea\.config\joplin-desktop\cache\nz.magnusso.zotero-link\zotero-link.js:1:1411)
    at C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\codemirror\lib\codemirror.js:3968:22
    at CodeMirror.setOption (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\codemirror\lib\codemirror.js:8304:52)
    at C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\Editor.js:238:24
    at commitHookEffectListMount (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24917:7)
    at commitPassiveMountEffects (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27078:3)
Component stack

    at Editor (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\Editor.js:76:54)
    at div
    at div
    at div
    at ErrorBoundary (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:12:9)
    at CodeMirror (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\CodeMirror.js:37:44)
    at div
    at div
    at div
    at NoteEditor (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteEditor.js:61:68)
    at ConnectFunction (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at div
    at I (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19269)
    at div
    at Resizable (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\re-resizable\lib\index.es5.js:220:28)
    at div
    at Resizable (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\re-resizable\lib\index.es5.js:220:28)
    at div
    at ResizableLayout (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\ResizableLayout\ResizableLayout.js:54:45)
    at div
    at MainScreenComponent (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:69:9)
    at ConnectFunction (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at div
    at NavigatorComponent (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\Navigator.js:7:1)
    at ConnectFunction (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at exports.ThemeProvider (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25001)
    at ae (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13440)
    at RootComponent (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\Root.js:93:1)
    at ConnectFunction (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at ErrorBoundary (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:12:9)
    at Provider (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:19:3)
Search...Error
The text editor encountered a fatal error and could not continue. The error might be due to a plugin, so please try to disable some of them and try again.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/jannessm/joplin-zotero-link/issues/new#), which will temporarily disable all plugins.

Message
Cannot read properties of undefined (reading 'completionSource')

Version info
Joplin for Desktop

Copyright © 2016-2024 Laurent Cozic
Joplin 3.1.24 (prod, win32)

Client ID: 833f47eae267427287c115a5114667e1
Sync Version: 3
Profile Version: 47
Keychain Supported: Yes

Revision: d581264

Backup: 1.4.2
Favorites: 1.3.2
Graph: 1.1.0
Jarvis: 0.9.1
Kminder Mindmap: 0.8.6
Link Graph UI: 1.5.0
Note Link System: 0.8.0
Note Tabs: 1.4.0
PlantUML2: 1.11.0
Quick Links: 1.3.2
Rich Markdown: 0.15.1
Templates: 2.4.0
Zotero Link: 2.0.1
Plugins
[
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": true,
        "version": "1.4.0"
    },
    {
        "id": "joplin.plugin.benji.favorites",
        "name": "Favorites",
        "enabled": true,
        "version": "1.3.2"
    },
    {
        "id": "com.whatever.quick-links",
        "name": "Quick Links",
        "enabled": true,
        "version": "1.3.2"
    },
    {
        "id": "ylc395.noteLinkSystem",
        "name": "Note Link System",
        "enabled": true,
        "version": "0.8.0"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": true,
        "version": "0.15.1"
    },
    {
        "id": "com.github.marc0l92.joplin-plugin-plantUML",
        "name": "PlantUML2",
        "enabled": true,
        "version": "1.11.0"
    },
    {
        "id": "calandra.kminder.joplin",
        "name": "Kminder Mindmap",
        "enabled": true,
        "version": "0.8.6"
    },
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.2"
    },
    {
        "id": "joplin-plugin-knowledge-graph",
        "name": "Graph",
        "enabled": true,
        "version": "1.1.0"
    },
    {
        "id": "joplin.plugin.templates",
        "name": "Templates",
        "enabled": true,
        "version": "2.4.0"
    },
    {
        "id": "joplin.plugin.alondmnt.jarvis",
        "name": "Jarvis",
        "enabled": true,
        "version": "0.9.1"
    },
    {
        "id": "io.treymo.LinkGraph",
        "name": "Link Graph UI",
        "enabled": true,
        "version": "1.5.0"
    },
    {
        "id": "nz.magnusso.zotero-link",
        "name": "Zotero Link",
        "enabled": true,
        "version": "2.0.1"
    }
]
Stack trace
TypeError: Cannot read properties of undefined (reading 'completionSource')
    at CodeMirror.<anonymous> (C:\Users\gaultiea\.config\joplin-desktop\cache\nz.magnusso.zotero-link\zotero-link.js:1:1411)
    at C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\codemirror\lib\codemirror.js:3968:22
    at CodeMirror.setOption (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\codemirror\lib\codemirror.js:8304:52)
    at C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\Editor.js:238:24
    at commitHookEffectListMount (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24917:7)
    at commitPassiveMountEffects (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27078:3)
Component stack

    at Editor (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\Editor.js:76:54)
    at div
    at div
    at div
    at ErrorBoundary (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:12:9)
    at CodeMirror (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\CodeMirror.js:37:44)
    at div
    at div
    at div
    at NoteEditor (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteEditor.js:61:68)
    at ConnectFunction (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at div
    at I (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19269)
    at div
    at Resizable (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\re-resizable\lib\index.es5.js:220:28)
    at div
    at Resizable (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\re-resizable\lib\index.es5.js:220:28)
    at div
    at ResizableLayout (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\ResizableLayout\ResizableLayout.js:54:45)
    at div
    at MainScreenComponent (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:69:9)
    at ConnectFunction (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at div
    at NavigatorComponent (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\Navigator.js:7:1)
    at ConnectFunction (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at exports.ThemeProvider (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25001)
    at ae (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13440)
    at RootComponent (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\Root.js:93:1)
    at ConnectFunction (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at ErrorBoundary (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:12:9)
    at Provider (C:\Users\gaultiea\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:19:3)

Thank you in advance for your help,

**Comment by jannessm** [comment]
Please install version 2.1.1 and check if the error persists

**Comment by KrullTheWarriorKing** [comment]
Thank you ! 
I tried to find the . jpl file for the plugin. 

I looked here : https://github.com/joplin/plugins?tab=readme-ov-file but it is an older version.

I looked on the app but it is the same. 

Then I looked here : https://github.com/jannessm/joplin-zotero-link/releases/tag/v2.1.1 

and downloaded both .zip and tar.gz but I did not find any .jpl file. 

So right now, **I do not know how to install the new version** (sorry .. I am sure it is easy ^^)

Could you help me ?

**Comment by jannessm** [comment]
Just update your version inside of Joplin :)

**Comment by KrullTheWarriorKing** [comment]
Sorry, but, I don't find any way to update the plugin in joplin : 

In the plugin board : 
![image](https://github.com/user-attachments/assets/01015cea-3f81-4119-a2ff-bcafdb93443e)

**Comment by jannessm** [comment]
please check again

**Comment by KrullTheWarriorKing** [comment]
Ok, I installed the latest version but the bug is still here, or at least I got this error : 

Error
The text editor encountered a fatal error and could not continue. The error might be due to a plugin, so please try to disable some of them and try again.

To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

If the error persists you may try to [restart in safe mode](https://github.com/jannessm/joplin-zotero-link/issues/22#), which will temporarily disable all plugins.

Message
Cannot read properties of undefined (reading 'completionSource')

Version info
Joplin for Desktop

Copyright © 2016-2025 Laurent Cozic
Joplin 3.0.15 (prod, win32)

ID client : 0529bacfb5a44470a3204394291eb5a1
Version de Synchro : 3
Version du profil : 47
Trousseau supporté : Oui

Révision : 598677b

Backup: 1.4.1
Graph: 1.1.0
Kminder Mindmap: 0.8.6
Link Graph UI: 1.5.0
Note Tabs: 1.4.0
PlantUML2: 1.11.0
Quick Links: 1.3.2
Quick Move: 1.1.0
Rich Markdown: 0.15.1
Templates: 2.4.0
Zotero Link: 2.1.1
Plugins
[
    {
        "id": "com.whatever.quick-links",
        "name": "Quick Links",
        "enabled": true,
        "version": "1.3.2"
    },
    {
        "id": "joplin.plugin.note.tabs",
        "name": "Note Tabs",
        "enabled": true,
        "version": "1.4.0"
    },
    {
        "id": "com.github.marc0l92.joplin-plugin-plantUML",
        "name": "PlantUML2",
        "enabled": true,
        "version": "1.11.0"
    },
    {
        "id": "plugin.calebjohn.rich-markdown",
        "name": "Rich Markdown",
        "enabled": true,
        "version": "0.15.1"
    },
    {
        "id": "joplin.plugin.benji.quick-move",
        "name": "Quick Move",
        "enabled": true,
        "version": "1.1.0"
    },
    {
        "id": "calandra.kminder.joplin",
        "name": "Kminder Mindmap",
        "enabled": true,
        "version": "0.8.6"
    },
    {
        "id": "io.github.jackgruber.backup",
        "name": "Backup",
        "enabled": true,
        "version": "1.4.1"
    },
    {
        "id": "joplin.plugin.templates",
        "name": "Templates",
        "enabled": true,
        "version": "2.4.0"
    },
    {
        "id": "joplin-plugin-knowledge-graph",
        "name": "Graph",
        "enabled": true,
        "version": "1.1.0"
    },
    {
        "id": "io.treymo.LinkGraph",
        "name": "Link Graph UI",
        "enabled": true,
        "version": "1.5.0"
    },
    {
        "id": "nz.magnusso.zotero-link",
        "name": "Zotero Link",
        "enabled": true,
        "version": "2.1.1"
    }
]
Stack trace
TypeError: Cannot read properties of undefined (reading 'completionSource')
    at CodeMirror.<anonymous> (C:\Users\gault\.config\joplin-desktop\cache\nz.magnusso.zotero-link\zotero-link.js:1:9670)
    at C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\codemirror\lib\codemirror.js:3968:22
    at CodeMirror.setOption (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\codemirror\lib\codemirror.js:8304:52)
    at C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\Editor.js:238:24
    at commitHookEffectListMount (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24878:7)
    at commitPassiveMountEffects (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:27039:3)
Component stack

    at Editor (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\Editor.js:76:54)
    at div
    at div
    at div
    at ErrorBoundary (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:21:9)
    at CodeMirror (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteBody\CodeMirror\v5\CodeMirror.js:46:44)
    at div
    at div
    at div
    at NoteEditor (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\NoteEditor\NoteEditor.js:70:68)
    at ConnectFunction (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at div
    at I (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:19269)
    at div
    at div
    at div
    at ResizableLayout (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\ResizableLayout\ResizableLayout.js:54:45)
    at div
    at MainScreenComponent (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\MainScreen\MainScreen.js:77:9)
    at ConnectFunction (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at div
    at NavigatorComponent (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\Navigator.js:7:1)
    at ConnectFunction (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at exports.ThemeProvider (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:25001)
    at ae (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\styled-components\dist\styled-components.cjs.js:1:13440)
    at RootComponent (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\Root.js:104:1)
    at ConnectFunction (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\connect.js:246:74)
    at ErrorBoundary (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\gui\ErrorBoundary.js:21:9)
    at Provider (C:\Users\gault\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\react-redux\lib\components\Provider.js:19:3)
    
    Thank yo for your help !

**Comment by goldroom** [comment]
Also just updated (update was not available before), same issue as @KrullTheWarriorKing .

**Comment by KrullTheWarriorKing** [comment]
Hello again, 

Thank you for the answer. 

I am on another computer and get the same issue. 

I realized that, there is nowhere in this issue or the previous solved issues, a simple explanation on "how to", either go to code mirror V6 or install a later version (<=1.2.1)

So, what I understand is that Codemirror V6 is in Joplin versions since some time now. So my question is, **why do I have code mirror V5 ?** 

The other way is to install a later version. Practical steps are 1) download a <=1.2  version of the  plugin on the github page, then 2) in the plugin page of joplin click on the "show advanced setting" button and add the path of the already downloaded plugin.

Thank you for your answer.

**Comment by KrullTheWarriorKing** [comment]
I Just resolved the issue by de-enabling the legacy editor which should have been the one using code mirror v5.
